name: Checks

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Setup Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: '24.4.1'

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          .yarn/install-state.gz
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

    - name: Install 
      run: yarn install --immutable

    - name: Install
      run: yarn install

    - name: Build
      run: yarn build
  
    - name: Lint
      run: yarn lint
